"""core schema

The five tables everything downstream reads from: filer, filer_cik, filing,
security, holding.

Hand-written, not autogenerated, and the generated column is why. Alembic
diffs SQLAlchemy metadata against a live schema and cannot see ``GENERATED
ALWAYS AS`` at all — it would emit ``filing.quarter`` as an ordinary nullable
text column, which would accept writes, drift from ``period_of_report``, and
look completely correct in every test that did not specifically go looking.

Two orderings in :func:`upgrade` are load-bearing rather than stylistic:

* ``filing`` carries ``UNIQUE (id, period_of_report)`` and it is created before
  ``holding``, because ``holding``'s composite foreign key references it and
  Postgres will not accept a foreign key against columns that are not uniquely
  constrained.
* the ``amendment_kind`` type is created before the table that uses it, by hand.
  ``op.create_table`` would emit ``CREATE TYPE`` implicitly, which is fine going
  up and useless coming down: ``drop_table`` does not drop the type, so a
  downgrade followed by an upgrade fails on "type already exists". Creating and
  dropping it explicitly makes the two directions symmetrical.

One thing to copy when writing the next migration: check constraints are named
*bare* here -- ``value_usd_is_not_negative``, not
``ck_holding_value_usd_is_not_negative``. The ``ck`` template in
``NAMING_CONVENTION`` interpolates ``%(constraint_name)s``, so it wraps whatever
name it is given rather than replacing it, and a pre-prefixed name lands in
Postgres as ``ck_holding_ck_holding_value_usd_is_not_negative``. The ``pk``,
``uq`` and ``fk`` templates interpolate no such token, so those names *are*
passed through verbatim and are spelled out in full below. The inconsistency is
SQLAlchemy's, not ours; the models are already written this way.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-27 01:20:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.db.models.filing import QUARTER_EXPRESSION

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# create_type=False: the type's lifecycle is managed by the explicit .create()
# and .drop() calls below, not as a side effect of the table that uses it.
AMENDMENT_KIND = postgresql.ENUM(
    "restatement",
    "new_holdings",
    name="amendment_kind",
    create_type=False,
)


def upgrade() -> None:
    AMENDMENT_KIND.create(op.get_bind(), checkfirst=False)

    op.create_table(
        "filer",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("first_period", sa.Date(), nullable=True),
        sa.Column("last_period", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_filer"),
        sa.UniqueConstraint("slug", name="uq_filer_slug"),
    )

    op.create_table(
        "filer_cik",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("filer_id", sa.BigInteger(), nullable=False),
        sa.Column("cik", sa.CHAR(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_filer_cik"),
        sa.ForeignKeyConstraint(
            ["filer_id"],
            ["filer.id"],
            name="fk_filer_cik_filer_id_filer",
            ondelete="CASCADE",
        ),
        # Many CIKs per filer, one filer per CIK. The AC's unique index, as the
        # constraint that backs one.
        sa.UniqueConstraint("cik", name="uq_filer_cik_cik"),
    )

    op.create_table(
        "security",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("cusip", sa.CHAR(length=9), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("ticker", sa.Text(), nullable=True),
        sa.Column("figi", sa.CHAR(length=12), nullable=True),
        sa.Column("resolution_source", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_security"),
        sa.UniqueConstraint("cusip", name="uq_security_cusip"),
        sa.CheckConstraint(
            "resolution_source IS NULL"
            " OR resolution_source IN ('openfigi', '13f_column', 'manual')",
            name="resolution_source_is_known",
        ),
    )

    # `quarter` is deliberately absent here and added by the ALTER below.
    op.create_table(
        "filing",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("accession_no", sa.CHAR(length=20), nullable=False),
        sa.Column("cik", sa.CHAR(length=10), nullable=False),
        sa.Column("filer_id", sa.BigInteger(), nullable=True),
        sa.Column("form_type", sa.Text(), nullable=False),
        sa.Column("period_of_report", sa.Date(), nullable=True),
        sa.Column("filed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value_multiplier", sa.SmallInteger(), nullable=False),
        sa.Column("amends_id", sa.BigInteger(), nullable=True),
        sa.Column("amendment_kind", AMENDMENT_KIND, nullable=True),
        sa.Column("report_type", sa.Text(), nullable=True),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_filing"),
        # The idempotency key. Everything in app/jobs is keyed on an accession
        # number and delivered at least once; this is what turns a redelivery
        # into a conflict to upsert on instead of a duplicate filing.
        sa.UniqueConstraint("accession_no", name="uq_filing_accession_no"),
        # Not queried. It exists so holding's composite FK has a unique target.
        sa.UniqueConstraint("id", "period_of_report", name="uq_filing_id_period_of_report"),
        sa.ForeignKeyConstraint(
            ["filer_id"],
            ["filer.id"],
            name="fk_filing_filer_id_filer",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["amends_id"],
            ["filing.id"],
            name="fk_filing_amends_id_filing",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "value_multiplier IN (1, 1000)",
            name="value_multiplier_is_one_or_one_thousand",
        ),
        sa.CheckConstraint(
            "form_type NOT LIKE '13F%' OR period_of_report IS NOT NULL",
            name="thirteen_f_has_a_period_of_report",
        ),
    )

    # The generated column, in raw DDL because there is no Alembic operation for
    # one. QUARTER_EXPRESSION is imported from the model so the two spellings
    # cannot drift; see the comment there for why it is not the `to_char` call
    # you would expect (short version: to_char is STABLE, and Postgres rejects a
    # non-IMMUTABLE generation expression outright).
    op.execute(
        sa.text(
            "ALTER TABLE filing "
            f"ADD COLUMN quarter text GENERATED ALWAYS AS ({QUARTER_EXPRESSION}) STORED"
        )
    )

    op.create_index("ix_filing_cik", "filing", ["cik"])
    op.create_index(
        "ix_filing_filer_id_period_of_report",
        "filing",
        ["filer_id", sa.text("period_of_report DESC")],
    )
    op.create_index("ix_filing_filed_at", "filing", [sa.text("filed_at DESC")])

    op.create_table(
        "holding",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("filing_id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("filer_id", sa.BigInteger(), nullable=False),
        sa.Column("period_of_report", sa.Date(), nullable=False),
        sa.Column("cusip", sa.CHAR(length=9), nullable=False),
        # numeric, not float, for every quantity below. These columns are summed
        # and compared for equality across quarters, and binary floating point
        # makes a sum depend on the order the planner returns rows in.
        sa.Column("value_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("shares", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("sshprnamt_type", sa.Text(), nullable=False),
        sa.Column("put_call", sa.Text(), nullable=True),
        sa.Column("investment_discretion", sa.Text(), nullable=True),
        sa.Column("voting_sole", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("voting_shared", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("voting_none", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_holding"),
        # NULLS NOT DISTINCT (Postgres 15+) is the whole constraint. put_call is
        # null on every common-stock row, and under Postgres's default NULL
        # handling those rows would never conflict with each other — so this key
        # would permit unlimited duplicates of the majority of the table, and
        # every re-ingest would silently double a portfolio.
        sa.UniqueConstraint(
            "filing_id",
            "cusip",
            "put_call",
            "sshprnamt_type",
            name="uq_holding_filing_id_cusip_put_call_sshprnamt_type",
            postgresql_nulls_not_distinct=True,
        ),
        # Carries referential integrity for filing_id *and* pins the denormalised
        # period_of_report to the filing's own, so the copy cannot drift.
        sa.ForeignKeyConstraint(
            ["filing_id", "period_of_report"],
            ["filing.id", "filing.period_of_report"],
            name="fk_holding_filing_id_period_of_report_filing",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name="fk_holding_security_id_security",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["filer_id"],
            ["filer.id"],
            name="fk_holding_filer_id_filer",
            ondelete="RESTRICT",
        ),
        # 13F is long-only. A negative is a parse error, not a short.
        sa.CheckConstraint("value_usd >= 0", name="value_usd_is_not_negative"),
        sa.CheckConstraint("shares >= 0", name="shares_is_not_negative"),
        sa.CheckConstraint(
            "sshprnamt_type IN ('SH', 'PRN')",
            name="sshprnamt_type_is_known",
        ),
        sa.CheckConstraint(
            "put_call IS NULL OR put_call IN ('Put', 'Call')",
            name="put_call_is_known",
        ),
    )

    op.create_index("ix_holding_filing_id", "holding", ["filing_id"])
    op.create_index("ix_holding_security_id", "holding", ["security_id"])
    op.create_index("ix_holding_cusip", "holding", ["cusip"])
    op.create_index(
        "ix_holding_filer_id_period_of_report",
        "holding",
        ["filer_id", "period_of_report"],
    )


def downgrade() -> None:
    """Drops all five tables and the enum type. This destroys every row in them.

    Reverse order of :func:`upgrade`, because the foreign keys run one way:
    holding references filing, security and filer; filing references filer;
    filer_cik references filer. Dropping filer first would fail on the
    dependency rather than cascade, which is the correct behaviour and the
    reason the order is written out rather than left to chance.

    The indexes are not dropped individually — ``DROP TABLE`` takes them, and
    the generated ``quarter`` column, with it. The type is dropped explicitly
    because nothing else will, and a leftover ``amendment_kind`` makes the next
    ``upgrade`` fail on "type already exists".
    """
    op.drop_table("holding")
    op.drop_table("filing")
    op.drop_table("security")
    op.drop_table("filer_cik")
    op.drop_table("filer")

    AMENDMENT_KIND.drop(op.get_bind(), checkfirst=False)
