"""Response models for ``GET /filings/{accession_no}``.

Hand-written rather than generated from the ORM classes, and the field list is
the point: this is the endpoint you open when a portfolio looks wrong, so it
carries the columns that record what ingestion *decided* —
:attr:`FilingRead.value_multiplier`, :attr:`FilingRead.parse_status`,
:attr:`FilingRead.parse_notes` — next to the numbers those decisions produced.
A model derived automatically from the table would carry them only by accident,
and would leak the next column somebody adds.
"""

from datetime import date, datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.api.schemas.types import Money, Quantity
from app.core.accession import ACCESSION_SHAPE
from app.db.models.enums import AmendmentKind

# Built straight from SQLAlchemy rows — ORM instances for the filing, Row
# objects for the holdings — so the routers never assemble a dict by hand.
_FROM_ROWS = ConfigDict(from_attributes=True)


class HoldingRead(BaseModel):
    """One reported position, as the filing wrote it plus what we resolved it to.

    ``cusip`` is the filing's own nine characters and ``issuer_name``/``ticker``
    are our interpretation of them, which is exactly the pair you want side by
    side when a position is attributed to the wrong company: a null ticker is an
    unresolved security, a wrong one is a bad resolution, and the CUSIP tells
    you which of the two you are looking at.
    """

    model_config = _FROM_ROWS

    cusip: str = Field(
        description="The nine characters this filing reported, as it reported them.",
        examples=["037833100"],
    )
    issuer_name: str | None = Field(
        default=None,
        description="From `security`, our resolution — not the issuer name this filing printed.",
        examples=["APPLE INC"],
    )
    ticker: str | None = Field(
        default=None,
        description="From `security`, our resolution. Null while the CUSIP is unresolved.",
        examples=["AAPL"],
    )

    value_usd: Money = Field(
        description=(
            "Whole dollars, always — already multiplied through by "
            "`value_multiplier`. Not comparable across `put_call`: an option "
            "line reports the notional value of the underlying, not a premium."
        ),
        examples=["2040000000.00"],
    )
    shares: Quantity = Field(
        description="A share count or a principal amount; `sshprnamt_type` says which.",
        examples=["12000000.0000"],
    )
    sshprnamt_type: str = Field(
        description="`SH` for shares, `PRN` for principal.", examples=["SH"]
    )
    put_call: str | None = Field(
        default=None,
        description="`Put`, `Call`, or null for the underlying itself.",
        examples=[None],
    )
    investment_discretion: str | None = Field(
        default=None,
        description=(
            "As the filing wrote it: `SOLE`, `DFND` (shared, defined) or `OTR` (shared, other)."
        ),
        examples=["SOLE"],
    )

    voting_sole: Quantity | None = Field(
        default=None,
        description="Shares the manager votes alone. Null when the filing left it out.",
        examples=["12000000.0000"],
    )
    voting_shared: Quantity | None = Field(
        default=None,
        description="Shares the manager votes with others. Null when the filing left it out.",
        examples=["0.0000"],
    )
    voting_none: Quantity | None = Field(
        default=None,
        description="Shares the manager does not vote. Null when the filing left it out.",
        examples=["0.0000"],
    )


class FilingRead(BaseModel):
    """A filing, its provenance, and every position it reports."""

    model_config = _FROM_ROWS

    accession_no: str = Field(
        description=f"EDGAR's identifier, dashed: `{ACCESSION_SHAPE}`.",
        examples=["0001067983-24-000011"],
    )
    cik: str = Field(
        description="As EDGAR filed it, zero-padded to ten. Not necessarily a resolved filer.",
        examples=["0001067983"],
    )
    form_type: str = Field(
        description="`13F-HR`, `13F-HR/A` for an amendment, or `13F-NT` for a notice.",
        examples=["13F-HR"],
    )
    period_of_report: date | None = Field(
        default=None,
        description=(
            "The quarter end being reported — never the filing date, which is "
            "45 days or more later."
        ),
        examples=["2024-03-31"],
    )
    quarter: str | None = Field(
        default=None,
        description="Generated by Postgres from `period_of_report`; null exactly when it is.",
        examples=["2024Q1"],
    )
    filed_at: datetime = Field(
        description="When it reached EDGAR.", examples=["2024-05-15T16:05:22Z"]
    )

    filer_id: int | None = Field(
        default=None,
        description="Null until this filing's CIK has been resolved to a filer.",
        examples=[1],
    )
    filer_name: str | None = Field(
        default=None,
        description="The resolved filer's name. Null where `filer_id` is.",
        examples=["Berkshire Hathaway"],
    )
    filer_slug: str | None = Field(
        default=None,
        description="The resolved filer's slug: `/v1/investors/{slug}`. Null where `filer_id` is.",
        examples=["berkshire-hathaway"],
    )

    value_multiplier: int = Field(
        description=(
            "Which units the filing's own `value` field used: 1000 before the "
            "2023-01-03 cutover, 1 on and after it. Recorded, not applied — "
            "`holdings[].value_usd` is already in whole dollars either way. This "
            "is the field to check first when a fund's total is out by 1000x."
        ),
        examples=[1],
    )
    amendment_no: int | None = Field(
        default=None,
        description=(
            "The cover page's amendment number, as the filer wrote it. Null on an "
            "original. Amendments apply in `filed_at` order, not in this order."
        ),
        examples=[1],
    )
    amendment_kind: AmendmentKind | None = Field(
        default=None,
        description="`restatement` replaces the original period; `new_holdings` adds to it.",
        examples=["restatement"],
    )
    amends_accession_no: str | None = Field(
        default=None,
        description="The filing this one amends, if any.",
        examples=["0000950123-24-005032"],
    )
    report_type: str | None = Field(
        default=None,
        description=(
            "Cover-page wording. A `NOTICE` reports no holdings at all; a "
            "`COMBINATION` reports only the part this manager holds directly."
        ),
        examples=["13F HOLDINGS REPORT"],
    )

    parse_status: str = Field(
        description=(
            "`pending` (fetched, not parsed), `ok`, `suspect` (loaded, but a "
            "normalisation guard fired — see `parse_notes`), or `failed` (not "
            "parsed at all; `parse_error` says why and there are no holdings)."
        ),
        examples=["ok"],
    )
    parse_notes: list[dict[str, Any]] | None = Field(
        default=None,
        description=(
            "Why a filing is `suspect`: one object per finding, with the row and CUSIP. "
            "`severity` is `error` for a guard that failed, which is what makes the filing "
            "`suspect`, or `warning` for evidence beside it."
        ),
        examples=[
            [
                {
                    "kind": "implied_price",
                    "severity": "error",
                    "cusip": "037833100",
                    "detail": "...",
                }
            ]
        ],
    )
    parse_error: str | None = Field(
        default=None,
        description="Set only alongside `parse_status: failed`.",
        examples=[None],
    )
    parsed_at: datetime | None = Field(
        default=None,
        description="When it was last parsed. Null while `parse_status` is `pending`.",
        examples=["2024-05-15T16:20:41Z"],
    )
    ingested_at: datetime = Field(
        description="When we first fetched it.", examples=["2024-05-15T16:20:39Z"]
    )

    raw_key: str | None = Field(
        default=None,
        description="Where the archived documents live: a prefix in the raw store.",
        examples=["raw/13f/1067983/0001067983-24-000011/"],
    )
    source_url: str | None = Field(
        default=None,
        description="The URL it was fetched from, stored rather than reconstructed.",
        examples=["https://www.sec.gov/Archives/edgar/data/1067983/000106798324000011/"],
    )

    holdings: list[HoldingRead] = Field(
        default_factory=list,
        description=(
            "Sorted by `value_usd` descending, largest position first. Empty for "
            "a 13F-NT, for a filing that failed to parse, and for one whose "
            "holdings have not been loaded yet."
        ),
    )
